# action.yml
name: 'Veracode Static Analysis Pipeline Scan and SARIF import'
description: 'Initiate a Veracode Static Analysis Pipeline Scan and convert the results file to a valid SARIF file'
inputs:
  scan-type:
    description: 'The report should be generated for the scan type specified'
    required: true
    default: 'pipeline'
  results-json:
    description: 'location of the policy or pipeline json result file'
    required: true
    default: 'results.json'
  pipeline-results-json:  # id of input
    description: 'location of the pipeline json result file'
    required: true
    default: 'results.json'
  output-results-sarif:  # id of input
    description: 'the path to the SARIF file as an output of the transformation'
    required: true
    default: 'veracode-results.sarif'  
  source-base-path-1:  
    description: 'a path prefix conversion before publish in the SARIF file'
    required: false
    default: ''
  source-base-path-2:  
    description: 'a path prefix conversion before publish in the SARIF file'
    required: false
    default: ''
  source-base-path-3:  
    description: 'a path prefix conversion before publish in the SARIF file'
    required: false
    default: ''
  finding-rule-level:
    description: 'The conversion rule of Veracode findings to GitHub level'
    required: true
    default: '4:3:0'
  repo_owner: 
    description: 'owner'
    required: false
  repo_name: 
    description: 'repo'
    required: false
  githubToken: 
    description: 'GitHub Token'
    required: true
    default: ${{ github.token }}
  ref:
    description: 'The git ref'
    required: true
    default: ${{ github.ref }}
  commitSHA:
    description: 'The git commit sha'
    required: true
    default: ${{ github.sha }}
runs:
  using: 'node20'
  main: 'dist/index.js'
