# action.yml
name: 'Convert Veracode Pipeline to SARIF'
description: 'Convert the output results file from Veracode Pipeline Scan to a valid SARIF file'
inputs:
  pipeline-results-json:  # id of input
    description: 'location of the pipeline json result file'
    required: true
    default: 'results.json'
  output-results-sarif:  # id of input
    description: 'the path to the SARIF file as an output of the transformation'
    required: true
    default: 'veracode-results.sarif'  
  source-base-path-1:  
    description: 'a path prefix conversion before publish in the SARIF file'
    required: false
    default: ''
  source-base-path-2:  
    description: 'a path prefix conversion before publish in the SARIF file'
    required: false
    default: ''
  source-base-path-3:  
    description: 'a path prefix conversion before publish in the SARIF file'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'convert-action.js'
